---
name: QA

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false  # Only new files
          VALIDATE_EDITORCONFIG: true
          VALIDATE_CSHARP: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
          YAML_CONFIG_FILE: .yamllint.yml
          VALIDATE_GITHUB_ACTIONS: true
  test:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
      - uses: actions/checkout@v3
        with:
          # Disabling shallow clone is required for Nerdbank.GitVersioning and SonarCloud to work properly
          fetch-depth: 0
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Install deps
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore
      - name: Run tests
        run: dotnet test -c Release --no-build --verbosity=minimal
