---
name: QA

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Full history is needed to get a proper list of changed files
          fetch-depth: 0
      - uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false  # Only changed files
          VALIDATE_EDITORCONFIG: true
          VALIDATE_CSHARP: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
          VALIDATE_GITHUB_ACTIONS: true
  sonarcloud:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
      - uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended by SonarCloud for improving relevancy of reporting
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            3.1.x
            6.0.x
            7.0.x
      - run: dotnet tool restore
      - run: dotnet gitversion /output buildserver
      - run: ./sonar-scan.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
